// Generated by CoffeeScript 1.9.1
(function() {
  var _;

  _ = module.exports;

  _.addClass = require('./modules/add_class.js');

  _.hasClass = require('./modules/has_class.js');

  _.removeClass = require('./modules/remove_class.js');

  _.toggleClass = require('./modules/toggle_class.js');

  _.getData = require('./modules/get_data.js');

}).call(this);
