// Generated by CoffeeScript 1.9.1
(function() {
  var Actions, a, isFunction, plugin, pubsub;

  pubsub = require('../utils/pubsub.js');

  isFunction = require('../utils/isType.js').Function;

  plugin = require('./plugin.js');

  Actions = (function() {
    var _actions;

    Actions.prototype.ACTIVE_ELEMENT = 'data-yaks-action-active';

    Actions.prototype.TYPE = 'data-yaks-action-type';

    _actions = {};

    function Actions() {
      pubsub.subscribe('load', this.findActions.bind(this));
      pubsub.subscribe('new_content', this.findActions.bind(this));
    }

    Actions.prototype.registerAction = function(name, action) {
      if (isFunction(action)) {
        return _actions[name] = action;
      }
    };

    Actions.prototype.findActions = function() {
      var action, i, len, ref, results;
      ref = document.querySelectorAll("[" + this.ACTIVE_ELEMENT + "]");
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        action = ref[i];
        results.push(this._fireAction(action));
      }
      return results;
    };

    Actions.prototype._fireAction = function(el) {
      var i, len, ref, type, types;
      types = el.getAttribute(this.TYPE);
      if (types == null) {
        return false;
      }
      ref = types.split('|');
      for (i = 0, len = ref.length; i < len; i++) {
        type = ref[i];
        if (_actions[type] != null) {
          _actions[type](el);
        }
      }
      return el.removeAttribute(this.ACTIVE_ELEMENT);
    };

    Actions.prototype._getActions = function() {
      return Object.create(_actions);
    };

    return Actions;

  })();

  module.exports = a = new Actions();

}).call(this);
