// Generated by CoffeeScript 1.11.1
(function() {
  var modules;

  modules = module.exports;

  modules.actions = require('./actions.js');

  modules.plugin = require('./plugin.js');

}).call(this);
