(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
// Generated by CoffeeScript 1.9.1
(function() {
  var _;

  _ = module.exports;

  _.addClass = require('./modules/add_class.js');

  _.hasClass = require('./modules/has_class.js');

  _.removeClass = require('./modules/remove_class.js');

  _.toggleClass = require('./modules/toggle_class.js');

}).call(this);

},{"./modules/add_class.js":2,"./modules/has_class.js":3,"./modules/remove_class.js":4,"./modules/toggle_class.js":5}],2:[function(require,module,exports){
// Generated by CoffeeScript 1.9.1
(function() {
  var addClass, hasClass;

  hasClass = require('./has_class.js');

  module.exports = addClass = function(el, className) {
    if (!hasClass(el, className)) {
      return el.className += " " + className;
    }
  };

}).call(this);

},{"./has_class.js":3}],3:[function(require,module,exports){
// Generated by CoffeeScript 1.9.1
(function() {
  var hasClass;

  module.exports = hasClass = function(el, className) {
    return new RegExp(" " + className + " ").test(" " + el.className + " ");
  };

}).call(this);

},{}],4:[function(require,module,exports){
// Generated by CoffeeScript 1.9.1
(function() {
  var hasClass, removeClass;

  hasClass = require('./has_class.js');

  module.exports = removeClass = function(el, className) {
    var classes;
    if (!hasClass(el, className)) {
      return false;
    }
    classes = " " + (el.className.replace(/[\t\r\n]/g, " ")) + " ";
    while (classes.indexOf(" " + className + " ") >= 0) {
      classes = classes.replace(" " + className + " ", " ");
    }
    return el.className = classes.replace(/^\s+|\s+$/g, "");
  };

}).call(this);

},{"./has_class.js":3}],5:[function(require,module,exports){
// Generated by CoffeeScript 1.9.1
(function() {
  var addClass, hasClass, removeClass, toggleClass;

  hasClass = require('./has_class.js');

  addClass = require('./add_class.js');

  removeClass = require('./remove_class.js');

  module.exports = toggleClass = function(el, className) {
    if (hasClass(el, className)) {
      return removeClass(el, className);
    } else {
      return addClass(el, className);
    }
  };

}).call(this);

},{"./add_class.js":2,"./has_class.js":3,"./remove_class.js":4}],6:[function(require,module,exports){
// Generated by CoffeeScript 1.9.1
(function() {
  var yaks;

  yaks = {
    DOM: require('./dom/index.js'),
    modules: require('./modules/index.js'),
    UTILS: require('./utils/index.js'),
    registerAction: require('./modules/actions.js').registerAction
  };

  window.yaks = yaks;

  module.exports = yaks;

}).call(this);

},{"./dom/index.js":1,"./modules/actions.js":7,"./modules/index.js":8,"./utils/index.js":11}],7:[function(require,module,exports){
// Generated by CoffeeScript 1.9.1
(function() {
  var Actions, a, isFunction, plugin, pubsub;

  pubsub = require('../utils/pubsub.js');

  isFunction = require('../utils/isType.js').Function;

  plugin = require('./plugin.js');

  Actions = (function() {
    var _actions;

    Actions.prototype.ACTIVE_ELEMENT = 'data-yaks-action-active';

    Actions.prototype.TYPE = 'data-yaks-action-type';

    _actions = {};

    function Actions() {
      pubsub.subscribe('load', this.findActions.bind(this));
      pubsub.subscribe('new_content', this.findActions.bind(this));
    }

    Actions.prototype.registerAction = function(name, action) {
      if (isFunction(action)) {
        return _actions[name] = action;
      }
    };

    Actions.prototype.findActions = function() {
      var action, i, len, ref, results;
      ref = document.querySelectorAll("[" + this.ACTIVE_ELEMENT + "]");
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        action = ref[i];
        results.push(this._fireAction(action));
      }
      return results;
    };

    Actions.prototype._fireAction = function(el) {
      var i, len, ref, type, types;
      types = el.getAttribute(this.TYPE);
      if (types == null) {
        return false;
      }
      ref = types.split('|');
      for (i = 0, len = ref.length; i < len; i++) {
        type = ref[i];
        if (_actions[type] != null) {
          _actions[type](el);
        }
      }
      return el.removeAttribute(this.ACTIVE_ELEMENT);
    };

    Actions.prototype._getActions = function() {
      return Object.create(_actions);
    };

    return Actions;

  })();

  module.exports = a = new Actions();

}).call(this);

},{"../utils/isType.js":12,"../utils/pubsub.js":13,"./plugin.js":9}],8:[function(require,module,exports){
// Generated by CoffeeScript 1.9.1
(function() {
  var modules;

  modules = module.exports;

  modules.actions = require('./actions.js');

  modules.plugin = require('./plugin.js');

}).call(this);

},{"./actions.js":7,"./plugin.js":9}],9:[function(require,module,exports){
// Generated by CoffeeScript 1.9.1
(function() {
  var Plugin, YaksPlugin, isFunction;

  isFunction = require('../utils/isType.js').Function;

  Plugin = (function() {
    Plugin.prototype.LIFECYCLE_METHODS = ['init', 'events', 'action'];

    function Plugin(el1) {
      var i, len, method, ref;
      this.el = el1;
      this.__autobind();
      ref = this.LIFECYCLE_METHODS;
      for (i = 0, len = ref.length; i < len; i++) {
        method = ref[i];
        if (typeof this[method] === "function") {
          this[method]();
        }
      }
      this;
    }

    Plugin.prototype.__autobind = function() {
      var bind, isBindable, method, results, that;
      that = this;
      isBindable = function(method) {
        return method !== '__autobind' && that.LIFECYCLE_METHODS.indexOf(method) === -1 && isFunction(that[method]) === true;
      };
      bind = function(method) {
        var bound;
        bound = function() {
          return arguments.callee._inherited.apply(that, arguments);
        };
        bound._inherited = that[method];
        return that[method] = bound;
      };
      results = [];
      for (method in this) {
        if (isBindable(method)) {
          results.push(bind(method));
        }
      }
      return results;
    };

    return Plugin;

  })();

  YaksPlugin = (function() {
    var _createNewClass;

    function YaksPlugin() {}

    YaksPlugin.prototype.create = function(methods) {
      var plugin;
      return plugin = function(el) {
        var klass;
        klass = _createNewClass(methods);
        return new klass(el);
      };
    };

    _createNewClass = function(methods) {
      var fn, hasProp, key, yaksPlugin;
      hasProp = {}.hasOwnProperty;
      yaksPlugin = function() {
        return this.constructor.apply(this, arguments);
      };
      yaksPlugin.prototype = Object.create(Plugin.prototype);
      for (key in methods) {
        fn = methods[key];
        if (!hasProp.call(yaksPlugin.prototype, key)) {
          yaksPlugin.prototype[key] = fn;
        }
      }
      return yaksPlugin;
    };

    return YaksPlugin;

  })();

  module.exports = new YaksPlugin();

}).call(this);

},{"../utils/isType.js":12}],10:[function(require,module,exports){
// Generated by CoffeeScript 1.9.1
(function() {
  var GlobalEvents, pubsub;

  pubsub = require('./pubsub.js');

  GlobalEvents = (function() {
    function GlobalEvents() {
      this.ready();
      this.resize();
      this.scroll();
    }

    GlobalEvents.prototype.ready = function() {
      document.addEventListener("DOMContentLoaded", this._ready_completed.bind(this), false);
      return window.addEventListener("load", this._ready_completed.bind(this), false);
    };

    GlobalEvents.prototype._ready_completed = function() {
      pubsub.publish('load');
      document.removeEventListener("DOMContentLoaded", this._ready_completed.bind(this), false);
      return window.removeEventListener("load", this._ready_completed.bind(this), false);
    };

    GlobalEvents.prototype.resize = function() {
      this.resizeTimer = null;
      window.addEventListener('onresize', this._resize_handler.bind(this));
      return window.addEventListener('resize', this._resize_handler.bind(this));
    };

    GlobalEvents.prototype._resize_handler = function() {
      if (this.resizeTimer) {
        clearTimeout(this.resizeTimer);
      }
      return this.resizeTimer = setTimeout(this._resize_fire.bind(this), 400);
    };

    GlobalEvents.prototype._resize_fire = function() {
      return pubsub.publish('resize', this._resize_get_breakpoint_name());
    };

    GlobalEvents.prototype._resize_get_breakpoint_name = function() {
      if (window.getComputedStyle == null) {
        return '';
      }
      return window.getComputedStyle(document.body, ':after').getPropertyValue('content').replace('-', '') || '';
    };

    GlobalEvents.prototype.scroll = function() {
      this.scrollTimer = null;
      window.addEventListener('onscroll', this._scroll_handler.bind(this));
      return window.addEventListener('scroll', this._scroll_handler.bind(this));
    };

    GlobalEvents.prototype._scroll_handler = function() {
      if (this.scrollTimer) {
        clearTimeout(this.scrollTimer);
      }
      return this.scrollTimer = setTimeout(this._scroll_fire.bind(this), 200);
    };

    GlobalEvents.prototype._scroll_fire = function() {
      return pubsub.publish('scroll');
    };

    return GlobalEvents;

  })();

  module.exports = new GlobalEvents();

}).call(this);

},{"./pubsub.js":13}],11:[function(require,module,exports){
// Generated by CoffeeScript 1.9.1
(function() {
  var utils;

  utils = module.exports;

  utils._globalEvents = require('./globalEvents.js');

  utils.pubsub = require('./pubsub.js');

  utils.is = require('./isType.js');

  utils.request = require('reqwest');

}).call(this);

},{"./globalEvents.js":10,"./isType.js":12,"./pubsub.js":13,"reqwest":14}],12:[function(require,module,exports){
// Generated by CoffeeScript 1.9.1
(function() {
  var IsType;

  IsType = (function() {
    function IsType() {}

    IsType.Function = function(obj) {
      return !!(obj && obj.constructor && obj.call && obj.apply);
    };

    return IsType;

  })();

  module.exports = IsType;

}).call(this);

},{}],13:[function(require,module,exports){
// Generated by CoffeeScript 1.9.1
(function() {
  var PubSub;

  PubSub = (function() {
    function PubSub(_subscriptions) {
      this._subscriptions = _subscriptions != null ? _subscriptions : {};
    }

    PubSub.prototype.subscribe = function(key, cb) {
      var cbs;
      (cbs = this._subscriptions[key] || []).push(cb);
      this._subscriptions[key] = cbs;
      return this;
    };

    PubSub.prototype.isSubscribed = function(key) {
      return Boolean(this._getMatches(key)[0].length);
    };

    PubSub.prototype.unsubscribe = function(key) {
      var found_key, j, len, ref, results;
      ref = this._getMatches(key)[0];
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        found_key = ref[j];
        results.push(this._removeFromObject(found_key));
      }
      return results;
    };

    PubSub.prototype.publish = function(key, args) {
      var j, k, len, len1, matches, ref, sub, subs;
      if (args == null) {
        args = [];
      }
      matches = this._getMatches(key);
      if (!matches[0].length) {
        return false;
      }
      args = args.constructor === Array ? args : [args];
      ref = matches[1];
      for (j = 0, len = ref.length; j < len; j++) {
        subs = ref[j];
        for (k = 0, len1 = subs.length; k < len1; k++) {
          sub = subs[k];
          sub.apply(sub, args);
        }
      }
      return this;
    };

    PubSub.prototype._getMatches = function(key) {
      var cb, keys, matches, ref, subKey;
      keys = [];
      matches = [];
      ref = this._subscriptions;
      for (subKey in ref) {
        cb = ref[subKey];
        if (!(this._isMatch(key, subKey))) {
          continue;
        }
        keys.push(subKey);
        matches.push(cb);
      }
      return [keys, matches];
    };

    PubSub.prototype._isMatch = function(subKey, _subKey) {
      var i, longerMessageLength, sub1Array, sub1Bitmask, sub2Array, sub2Bitmask;
      sub1Array = _subKey.split('.');
      sub2Array = subKey.split('.');
      sub1Bitmask = '';
      sub2Bitmask = '';
      longerMessageLength = sub1Array.length >= sub2Array.length ? sub1Array.length : sub2Array.length;
      if (_subKey === subKey) {
        return true;
      }
      if (sub1Array.length !== sub2Array.length) {
        return false;
      }
      i = 0;
      while (i < longerMessageLength) {
        if (sub1Array[i] !== '*' && sub2Array[i] !== '*' && sub1Array[i] !== sub2Array[i]) {
          return false;
        }
        sub1Bitmask += sub1Array[i] === '*' ? '0' : '1';
        sub2Bitmask += sub2Array[i] === '*' ? '0' : '1';
        i++;
      }
      return sub1Bitmask >= sub2Bitmask;
    };

    PubSub.prototype._removeFromObject = function(key) {
      var error;
      try {
        return delete this._subscriptions[key];
      } catch (_error) {
        error = _error;
        return this._subscriptions[key] = void 0;
      }
    };

    return PubSub;

  })();

  module.exports = new PubSub();

}).call(this);

},{}],14:[function(require,module,exports){
/*!
  * Reqwest! A general purpose XHR connection manager
  * license MIT (c) Dustin Diaz 2014
  * https://github.com/ded/reqwest
  */

!function (name, context, definition) {
  if (typeof module != 'undefined' && module.exports) module.exports = definition()
  else if (typeof define == 'function' && define.amd) define(definition)
  else context[name] = definition()
}('reqwest', this, function () {

  var win = window
    , doc = document
    , httpsRe = /^http/
    , protocolRe = /(^\w+):\/\//
    , twoHundo = /^(20\d|1223)$/ //http://stackoverflow.com/questions/10046972/msie-returns-status-code-of-1223-for-ajax-request
    , byTag = 'getElementsByTagName'
    , readyState = 'readyState'
    , contentType = 'Content-Type'
    , requestedWith = 'X-Requested-With'
    , head = doc[byTag]('head')[0]
    , uniqid = 0
    , callbackPrefix = 'reqwest_' + (+new Date())
    , lastValue // data stored by the most recent JSONP callback
    , xmlHttpRequest = 'XMLHttpRequest'
    , xDomainRequest = 'XDomainRequest'
    , noop = function () {}

    , isArray = typeof Array.isArray == 'function'
        ? Array.isArray
        : function (a) {
            return a instanceof Array
          }

    , defaultHeaders = {
          'contentType': 'application/x-www-form-urlencoded'
        , 'requestedWith': xmlHttpRequest
        , 'accept': {
              '*':  'text/javascript, text/html, application/xml, text/xml, */*'
            , 'xml':  'application/xml, text/xml'
            , 'html': 'text/html'
            , 'text': 'text/plain'
            , 'json': 'application/json, text/javascript'
            , 'js':   'application/javascript, text/javascript'
          }
      }

    , xhr = function(o) {
        // is it x-domain
        if (o['crossOrigin'] === true) {
          var xhr = win[xmlHttpRequest] ? new XMLHttpRequest() : null
          if (xhr && 'withCredentials' in xhr) {
            return xhr
          } else if (win[xDomainRequest]) {
            return new XDomainRequest()
          } else {
            throw new Error('Browser does not support cross-origin requests')
          }
        } else if (win[xmlHttpRequest]) {
          return new XMLHttpRequest()
        } else {
          return new ActiveXObject('Microsoft.XMLHTTP')
        }
      }
    , globalSetupOptions = {
        dataFilter: function (data) {
          return data
        }
      }

  function succeed(r) {
    var protocol = protocolRe.exec(r.url);
    protocol = (protocol && protocol[1]) || window.location.protocol;
    return httpsRe.test(protocol) ? twoHundo.test(r.request.status) : !!r.request.response;
  }

  function handleReadyState(r, success, error) {
    return function () {
      // use _aborted to mitigate against IE err c00c023f
      // (can't read props on aborted request objects)
      if (r._aborted) return error(r.request)
      if (r._timedOut) return error(r.request, 'Request is aborted: timeout')
      if (r.request && r.request[readyState] == 4) {
        r.request.onreadystatechange = noop
        if (succeed(r)) success(r.request)
        else
          error(r.request)
      }
    }
  }

  function setHeaders(http, o) {
    var headers = o['headers'] || {}
      , h

    headers['Accept'] = headers['Accept']
      || defaultHeaders['accept'][o['type']]
      || defaultHeaders['accept']['*']

    var isAFormData = typeof FormData === 'function' && (o['data'] instanceof FormData);
    // breaks cross-origin requests with legacy browsers
    if (!o['crossOrigin'] && !headers[requestedWith]) headers[requestedWith] = defaultHeaders['requestedWith']
    if (!headers[contentType] && !isAFormData) headers[contentType] = o['contentType'] || defaultHeaders['contentType']
    for (h in headers)
      headers.hasOwnProperty(h) && 'setRequestHeader' in http && http.setRequestHeader(h, headers[h])
  }

  function setCredentials(http, o) {
    if (typeof o['withCredentials'] !== 'undefined' && typeof http.withCredentials !== 'undefined') {
      http.withCredentials = !!o['withCredentials']
    }
  }

  function generalCallback(data) {
    lastValue = data
  }

  function urlappend (url, s) {
    return url + (/\?/.test(url) ? '&' : '?') + s
  }

  function handleJsonp(o, fn, err, url) {
    var reqId = uniqid++
      , cbkey = o['jsonpCallback'] || 'callback' // the 'callback' key
      , cbval = o['jsonpCallbackName'] || reqwest.getcallbackPrefix(reqId)
      , cbreg = new RegExp('((^|\\?|&)' + cbkey + ')=([^&]+)')
      , match = url.match(cbreg)
      , script = doc.createElement('script')
      , loaded = 0
      , isIE10 = navigator.userAgent.indexOf('MSIE 10.0') !== -1

    if (match) {
      if (match[3] === '?') {
        url = url.replace(cbreg, '$1=' + cbval) // wildcard callback func name
      } else {
        cbval = match[3] // provided callback func name
      }
    } else {
      url = urlappend(url, cbkey + '=' + cbval) // no callback details, add 'em
    }

    win[cbval] = generalCallback

    script.type = 'text/javascript'
    script.src = url
    script.async = true
    if (typeof script.onreadystatechange !== 'undefined' && !isIE10) {
      // need this for IE due to out-of-order onreadystatechange(), binding script
      // execution to an event listener gives us control over when the script
      // is executed. See http://jaubourg.net/2010/07/loading-script-as-onclick-handler-of.html
      script.htmlFor = script.id = '_reqwest_' + reqId
    }

    script.onload = script.onreadystatechange = function () {
      if ((script[readyState] && script[readyState] !== 'complete' && script[readyState] !== 'loaded') || loaded) {
        return false
      }
      script.onload = script.onreadystatechange = null
      script.onclick && script.onclick()
      // Call the user callback with the last value stored and clean up values and scripts.
      fn(lastValue)
      lastValue = undefined
      head.removeChild(script)
      loaded = 1
    }

    // Add the script to the DOM head
    head.appendChild(script)

    // Enable JSONP timeout
    return {
      abort: function () {
        script.onload = script.onreadystatechange = null
        err({}, 'Request is aborted: timeout', {})
        lastValue = undefined
        head.removeChild(script)
        loaded = 1
      }
    }
  }

  function getRequest(fn, err) {
    var o = this.o
      , method = (o['method'] || 'GET').toUpperCase()
      , url = typeof o === 'string' ? o : o['url']
      // convert non-string objects to query-string form unless o['processData'] is false
      , data = (o['processData'] !== false && o['data'] && typeof o['data'] !== 'string')
        ? reqwest.toQueryString(o['data'])
        : (o['data'] || null)
      , http
      , sendWait = false

    // if we're working on a GET request and we have data then we should append
    // query string to end of URL and not post data
    if ((o['type'] == 'jsonp' || method == 'GET') && data) {
      url = urlappend(url, data)
      data = null
    }

    if (o['type'] == 'jsonp') return handleJsonp(o, fn, err, url)

    // get the xhr from the factory if passed
    // if the factory returns null, fall-back to ours
    http = (o.xhr && o.xhr(o)) || xhr(o)

    http.open(method, url, o['async'] === false ? false : true)
    setHeaders(http, o)
    setCredentials(http, o)
    if (win[xDomainRequest] && http instanceof win[xDomainRequest]) {
        http.onload = fn
        http.onerror = err
        // NOTE: see
        // http://social.msdn.microsoft.com/Forums/en-US/iewebdevelopment/thread/30ef3add-767c-4436-b8a9-f1ca19b4812e
        http.onprogress = function() {}
        sendWait = true
    } else {
      http.onreadystatechange = handleReadyState(this, fn, err)
    }
    o['before'] && o['before'](http)
    if (sendWait) {
      setTimeout(function () {
        http.send(data)
      }, 200)
    } else {
      http.send(data)
    }
    return http
  }

  function Reqwest(o, fn) {
    this.o = o
    this.fn = fn

    init.apply(this, arguments)
  }

  function setType(header) {
    // json, javascript, text/plain, text/html, xml
    if (header.match('json')) return 'json'
    if (header.match('javascript')) return 'js'
    if (header.match('text')) return 'html'
    if (header.match('xml')) return 'xml'
  }

  function init(o, fn) {

    this.url = typeof o == 'string' ? o : o['url']
    this.timeout = null

    // whether request has been fulfilled for purpose
    // of tracking the Promises
    this._fulfilled = false
    // success handlers
    this._successHandler = function(){}
    this._fulfillmentHandlers = []
    // error handlers
    this._errorHandlers = []
    // complete (both success and fail) handlers
    this._completeHandlers = []
    this._erred = false
    this._responseArgs = {}

    var self = this

    fn = fn || function () {}

    if (o['timeout']) {
      this.timeout = setTimeout(function () {
        timedOut()
      }, o['timeout'])
    }

    if (o['success']) {
      this._successHandler = function () {
        o['success'].apply(o, arguments)
      }
    }

    if (o['error']) {
      this._errorHandlers.push(function () {
        o['error'].apply(o, arguments)
      })
    }

    if (o['complete']) {
      this._completeHandlers.push(function () {
        o['complete'].apply(o, arguments)
      })
    }

    function complete (resp) {
      o['timeout'] && clearTimeout(self.timeout)
      self.timeout = null
      while (self._completeHandlers.length > 0) {
        self._completeHandlers.shift()(resp)
      }
    }

    function success (resp) {
      var type = o['type'] || resp && setType(resp.getResponseHeader('Content-Type')) // resp can be undefined in IE
      resp = (type !== 'jsonp') ? self.request : resp
      // use global data filter on response text
      var filteredResponse = globalSetupOptions.dataFilter(resp.responseText, type)
        , r = filteredResponse
      try {
        resp.responseText = r
      } catch (e) {
        // can't assign this in IE<=8, just ignore
      }
      if (r) {
        switch (type) {
        case 'json':
          try {
            resp = win.JSON ? win.JSON.parse(r) : eval('(' + r + ')')
          } catch (err) {
            return error(resp, 'Could not parse JSON in response', err)
          }
          break
        case 'js':
          resp = eval(r)
          break
        case 'html':
          resp = r
          break
        case 'xml':
          resp = resp.responseXML
              && resp.responseXML.parseError // IE trololo
              && resp.responseXML.parseError.errorCode
              && resp.responseXML.parseError.reason
            ? null
            : resp.responseXML
          break
        }
      }

      self._responseArgs.resp = resp
      self._fulfilled = true
      fn(resp)
      self._successHandler(resp)
      while (self._fulfillmentHandlers.length > 0) {
        resp = self._fulfillmentHandlers.shift()(resp)
      }

      complete(resp)
    }

    function timedOut() {
      self._timedOut = true
      self.request.abort()      
    }

    function error(resp, msg, t) {
      resp = self.request
      self._responseArgs.resp = resp
      self._responseArgs.msg = msg
      self._responseArgs.t = t
      self._erred = true
      while (self._errorHandlers.length > 0) {
        self._errorHandlers.shift()(resp, msg, t)
      }
      complete(resp)
    }

    this.request = getRequest.call(this, success, error)
  }

  Reqwest.prototype = {
    abort: function () {
      this._aborted = true
      this.request.abort()
    }

  , retry: function () {
      init.call(this, this.o, this.fn)
    }

    /**
     * Small deviation from the Promises A CommonJs specification
     * http://wiki.commonjs.org/wiki/Promises/A
     */

    /**
     * `then` will execute upon successful requests
     */
  , then: function (success, fail) {
      success = success || function () {}
      fail = fail || function () {}
      if (this._fulfilled) {
        this._responseArgs.resp = success(this._responseArgs.resp)
      } else if (this._erred) {
        fail(this._responseArgs.resp, this._responseArgs.msg, this._responseArgs.t)
      } else {
        this._fulfillmentHandlers.push(success)
        this._errorHandlers.push(fail)
      }
      return this
    }

    /**
     * `always` will execute whether the request succeeds or fails
     */
  , always: function (fn) {
      if (this._fulfilled || this._erred) {
        fn(this._responseArgs.resp)
      } else {
        this._completeHandlers.push(fn)
      }
      return this
    }

    /**
     * `fail` will execute when the request fails
     */
  , fail: function (fn) {
      if (this._erred) {
        fn(this._responseArgs.resp, this._responseArgs.msg, this._responseArgs.t)
      } else {
        this._errorHandlers.push(fn)
      }
      return this
    }
  , 'catch': function (fn) {
      return this.fail(fn)
    }
  }

  function reqwest(o, fn) {
    return new Reqwest(o, fn)
  }

  // normalize newline variants according to spec -> CRLF
  function normalize(s) {
    return s ? s.replace(/\r?\n/g, '\r\n') : ''
  }

  function serial(el, cb) {
    var n = el.name
      , t = el.tagName.toLowerCase()
      , optCb = function (o) {
          // IE gives value="" even where there is no value attribute
          // 'specified' ref: http://www.w3.org/TR/DOM-Level-3-Core/core.html#ID-862529273
          if (o && !o['disabled'])
            cb(n, normalize(o['attributes']['value'] && o['attributes']['value']['specified'] ? o['value'] : o['text']))
        }
      , ch, ra, val, i

    // don't serialize elements that are disabled or without a name
    if (el.disabled || !n) return

    switch (t) {
    case 'input':
      if (!/reset|button|image|file/i.test(el.type)) {
        ch = /checkbox/i.test(el.type)
        ra = /radio/i.test(el.type)
        val = el.value
        // WebKit gives us "" instead of "on" if a checkbox has no value, so correct it here
        ;(!(ch || ra) || el.checked) && cb(n, normalize(ch && val === '' ? 'on' : val))
      }
      break
    case 'textarea':
      cb(n, normalize(el.value))
      break
    case 'select':
      if (el.type.toLowerCase() === 'select-one') {
        optCb(el.selectedIndex >= 0 ? el.options[el.selectedIndex] : null)
      } else {
        for (i = 0; el.length && i < el.length; i++) {
          el.options[i].selected && optCb(el.options[i])
        }
      }
      break
    }
  }

  // collect up all form elements found from the passed argument elements all
  // the way down to child elements; pass a '<form>' or form fields.
  // called with 'this'=callback to use for serial() on each element
  function eachFormElement() {
    var cb = this
      , e, i
      , serializeSubtags = function (e, tags) {
          var i, j, fa
          for (i = 0; i < tags.length; i++) {
            fa = e[byTag](tags[i])
            for (j = 0; j < fa.length; j++) serial(fa[j], cb)
          }
        }

    for (i = 0; i < arguments.length; i++) {
      e = arguments[i]
      if (/input|select|textarea/i.test(e.tagName)) serial(e, cb)
      serializeSubtags(e, [ 'input', 'select', 'textarea' ])
    }
  }

  // standard query string style serialization
  function serializeQueryString() {
    return reqwest.toQueryString(reqwest.serializeArray.apply(null, arguments))
  }

  // { 'name': 'value', ... } style serialization
  function serializeHash() {
    var hash = {}
    eachFormElement.apply(function (name, value) {
      if (name in hash) {
        hash[name] && !isArray(hash[name]) && (hash[name] = [hash[name]])
        hash[name].push(value)
      } else hash[name] = value
    }, arguments)
    return hash
  }

  // [ { name: 'name', value: 'value' }, ... ] style serialization
  reqwest.serializeArray = function () {
    var arr = []
    eachFormElement.apply(function (name, value) {
      arr.push({name: name, value: value})
    }, arguments)
    return arr
  }

  reqwest.serialize = function () {
    if (arguments.length === 0) return ''
    var opt, fn
      , args = Array.prototype.slice.call(arguments, 0)

    opt = args.pop()
    opt && opt.nodeType && args.push(opt) && (opt = null)
    opt && (opt = opt.type)

    if (opt == 'map') fn = serializeHash
    else if (opt == 'array') fn = reqwest.serializeArray
    else fn = serializeQueryString

    return fn.apply(null, args)
  }

  reqwest.toQueryString = function (o, trad) {
    var prefix, i
      , traditional = trad || false
      , s = []
      , enc = encodeURIComponent
      , add = function (key, value) {
          // If value is a function, invoke it and return its value
          value = ('function' === typeof value) ? value() : (value == null ? '' : value)
          s[s.length] = enc(key) + '=' + enc(value)
        }
    // If an array was passed in, assume that it is an array of form elements.
    if (isArray(o)) {
      for (i = 0; o && i < o.length; i++) add(o[i]['name'], o[i]['value'])
    } else {
      // If traditional, encode the "old" way (the way 1.3.2 or older
      // did it), otherwise encode params recursively.
      for (prefix in o) {
        if (o.hasOwnProperty(prefix)) buildParams(prefix, o[prefix], traditional, add)
      }
    }

    // spaces should be + according to spec
    return s.join('&').replace(/%20/g, '+')
  }

  function buildParams(prefix, obj, traditional, add) {
    var name, i, v
      , rbracket = /\[\]$/

    if (isArray(obj)) {
      // Serialize array item.
      for (i = 0; obj && i < obj.length; i++) {
        v = obj[i]
        if (traditional || rbracket.test(prefix)) {
          // Treat each array item as a scalar.
          add(prefix, v)
        } else {
          buildParams(prefix + '[' + (typeof v === 'object' ? i : '') + ']', v, traditional, add)
        }
      }
    } else if (obj && obj.toString() === '[object Object]') {
      // Serialize object item.
      for (name in obj) {
        buildParams(prefix + '[' + name + ']', obj[name], traditional, add)
      }

    } else {
      // Serialize scalar item.
      add(prefix, obj)
    }
  }

  reqwest.getcallbackPrefix = function () {
    return callbackPrefix
  }

  // jQuery and Zepto compatibility, differences can be remapped here so you can call
  // .ajax.compat(options, callback)
  reqwest.compat = function (o, fn) {
    if (o) {
      o['type'] && (o['method'] = o['type']) && delete o['type']
      o['dataType'] && (o['type'] = o['dataType'])
      o['jsonpCallback'] && (o['jsonpCallbackName'] = o['jsonpCallback']) && delete o['jsonpCallback']
      o['jsonp'] && (o['jsonpCallback'] = o['jsonp'])
    }
    return new Reqwest(o, fn)
  }

  reqwest.ajaxSetup = function (options) {
    options = options || {}
    for (var k in options) {
      globalSetupOptions[k] = options[k]
    }
  }

  return reqwest
});

},{}]},{},[6]);
