// Generated by CoffeeScript 1.11.1
(function() {
  var canUseDOM;

  module.exports = canUseDOM = !!(typeof window !== 'undefined' && window.document && window.document.createElement);

}).call(this);
