// Generated by CoffeeScript 1.9.1
(function() {
  var GlobalEvents, canUseDOM, pubsub;

  pubsub = require('./pubsub.js');

  canUseDOM = require('./canUseDOM.js');

  GlobalEvents = (function() {
    function GlobalEvents() {}

    return GlobalEvents;

  })();

  module.exports = new GlobalEvents();

}).call(this);
