// Generated by CoffeeScript 1.11.1
(function() {
  var IsType;

  IsType = (function() {
    function IsType() {}

    IsType.Function = function(obj) {
      return !!(obj && obj.constructor && obj.call && obj.apply);
    };

    return IsType;

  })();

  module.exports = IsType;

}).call(this);
