// Generated by CoffeeScript 1.9.1
(function() {
  var addClass, hasClass;

  hasClass = require('./has_class.js');

  module.exports = addClass = function(el, className) {
    if (!hasClass(el, className)) {
      return el.className += " " + className;
    }
  };

}).call(this);
