// Generated by CoffeeScript 1.9.1
(function() {
  var closest;

  module.exports = closest = function(el, tagname) {
    tagname = tagname.toLowerCase();
    while (true) {
      if (el.nodeName.toLowerCase() === tagname) {
        return el;
      }
      if (!(el = el.parentNode)) {
        break;
      }
    }
    return null;
  };

}).call(this);
