// Generated by CoffeeScript 1.9.1
(function() {
  var getData;

  module.exports = getData = function(el) {
    var attr, data, i, len, ref;
    data = {};
    ref = el.attributes;
    for (i = 0, len = ref.length; i < len; i++) {
      attr = ref[i];
      if (/^data-/.test(attr.name)) {
        data[attr.name] = attr.value;
      }
    }
    return data;
  };

}).call(this);
