// Generated by CoffeeScript 1.11.1
(function() {
  var hasClass;

  module.exports = hasClass = function(el, className) {
    return new RegExp(" " + className + " ").test(" " + el.className + " ");
  };

}).call(this);
