// Generated by CoffeeScript 1.9.1
(function() {
  var hasClass, removeClass;

  hasClass = require('./has_class.js');

  module.exports = removeClass = function(el, className) {
    var classes;
    if (!hasClass(el, className)) {
      return false;
    }
    classes = " " + (el.className.replace(/[\t\r\n]/g, " ")) + " ";
    while (classes.indexOf(" " + className + " ") >= 0) {
      classes = classes.replace(" " + className + " ", " ");
    }
    return el.className = classes.replace(/^\s+|\s+$/g, "");
  };

}).call(this);
