// Generated by CoffeeScript 1.9.1
(function() {
  var addClass, hasClass, removeClass, toggleClass;

  hasClass = require('./has_class.js');

  addClass = require('./add_class.js');

  removeClass = require('./remove_class.js');

  module.exports = toggleClass = function(el, className) {
    if (hasClass(el, className)) {
      return removeClass(el, className);
    } else {
      return addClass(el, className);
    }
  };

}).call(this);
